Сделал дз по методу filter
FenZlo/Homework pull request #3
Opened 2022-12-27 17:26 UTC by FenZlo

Не получаются тесты. Я сделал все по аналогии, как мы делали, что-то сделал неправильно. Ещё не разобрался, как работать с нодой и с тестами :(

2022-12-27 18:11 UTC, EvgenyPlotnikov45 requested changes

2022-12-27 18:11 UTC, EvgenyPlotnikov45 commented on src/filter-by-query.js
> +    let Arr = array.filter(function (el) {
тут можно сразу писать
```suggestion
    return array.filter(function (el) {
```

2022-12-27 18:11 UTC, EvgenyPlotnikov45 commented on tests/filter-by-query.js
> +    assert.strictEqual(filterByQuery(['Москва', 'Казань', 'Тобольск'], 'а'))
вторым параметром у тебя ничего не передано, значит у тебя тут тест на undefined) типо функция твоя должна вернуть undefined чтобы тест прошел, тебе тут надо проверить, что ожидается массив ['Москва', 'Казань']

2022-12-27 18:11 UTC, EvgenyPlotnikov45 commented on tests/filter-by-query.js
> +    assert.strictEqual(filterByQuery(['Москва', 'Казань', 'Тобольск'], 'а'))
а еще скорее всего strictEqual тут не подойдет, потому что ты сравниваешь массивы, strictEqual может сравнивать через оператор строгого сравнения ===, скажешь почему для массивов это не сработает? т.е. почему [] === [] выдаст false?

2022-12-27 18:11 UTC, EvgenyPlotnikov45 commented on tests/index.js
> +require('./filter-by-query.js');
расширение файла не нужно указывать
```suggestion
require('./filter-by-query');
```

2023-01-02 13:23 UTC, EvgenyPlotnikov45 approved these changes

2023-01-07 21:16 UTC, AtnesNess commented on src/map-method.js
> +        result += content.charAt(Math.floor(Math.random() * contentLength));
можно сделать сильно короче используя `new Array(length).fill('').map(() => ...).join('')`
https://medium.com/@wisecobbler/4-ways-to-populate-an-array-in-javascript-836952aea79f

необязательно, но будет клево если разберешься

2023-01-07 21:16 UTC, AtnesNess commented on src/map-method.js
> +function makeRandomLetter(length) {
лучше бы назвать makeRandomString наверное, так как по текущему названию создается впечатление что будет возвращена одна буква

2023-01-07 21:16 UTC, AtnesNess commented on src/sort-method.js
> +    if (a.length < b.length) {
советую изучить методы работы с sort, так как тоже можно сильно облегчить запись 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort

По сути можно было бы написать так 
```
function sortMethod (array) {
    return array.sort((a, b) => a - b)
}
```

2023-01-07 21:16 UTC, AtnesNess commented on tests/map-method.js
> +    assert.strictEqual(mapMethod([2,3,4,5,6,7,8,9]), true);
данное сравнение не верно так как нужно как минимум сравнить со строкой. 

Я бы посоветовал использовать assert.match и сравнить с регулярным выражением 
https://www.geeksforgeeks.org/node-js-assert-match-function/

про регэкспы: https://habr.com/ru/post/545150/

Если же их не использовать то тогда придется делать несколько assert.strictEqual для каждого теста

```
const result = mapMethod([1,2,3]);
assert.strictEqual(result[0], '1');
assert.strictEqual(isLetter(result[1]), true);
assert.strictEqual(isLetter(result[2]), true);
assert.strictEqual(isLetter(result[3]), true);
assert.strictEqual(result[4], '2');
```

где `isLetter` это доп функция которая будет проверять является ли аргумент буквой

2023-01-07 21:16 UTC, AtnesNess commented on tests/map-method.js
> +test('Concat with string', t => {
кстати плохой подход кидать кучу примеров в один тест, делай несколько тестов в одном файле

```
test('map method', t => {
   // subtests
   t.test('Should concat every array item with 3 letters and convert into string', () => {
      ....
   })

   t.test('Should return empty string for empty array', () => {
      ....
   })

   t.test('Should throw error if argument is not array', () => {
      ....
   })
})
```

смотри раздел subtests 

https://www.npmjs.com/package/test

2023-01-07 21:16 UTC, AtnesNess commented on tests/map-method.js
> +test('Concat with string', t => {
А вообще есть куча разных библиотек для тестирования и стандартный test  не очень удобный. Советую попробовать `jest`  https://jestjs.io/docs/25.x/getting-started

2023-01-07 21:16 UTC, AtnesNess commented on src/map-method.js
> +    let content = 'abcdefghijklmnopqrstuvwxyz';
просто заметка

в целом в памяти все хранится в конечном итоге в цифровом виде, и также для js у каждой буквы есть свое цифровое значение в памяти. (В зависимости от кодировки это значение разное, JS использует `UTF-16`, но пока туда можно не лезть так как у JS можно об этом не париться в отличие от python)

оно достается с помощью `'a'.charCodeAt(0)`. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt

тоесть по идее ты можешь зная длину алфавита (26 букв) или взяв `charCodeAt` для буквы 'z' просто генерировать число в этом диапазоне

Чтобы конвертировать число обратно в букву используется статичный метод fromCharCode
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/fromCharCode

```
const A_CODE = 'a'.charCodeAt(0);
const Z_CODE = 'z'.charCodeAt(0)
const ALPHABET_LENGTH = Z_CODE - A_CODE;

function makeRandomLetter() {
   const randomLetterCode = Math.floor(Math.random() * contentLength);
   
  return String.fromCharCode(randomLetterCode);
}
```

Таким образом тебе не нужно хранить в памяти весь алфавит в твоей функции


Но опять же это не частый случай, но просто хорошо знать об этом

2023-01-29 18:00 UTC, FenZlo commented on src/map-method.js
> +        result += content.charAt(Math.floor(Math.random() * contentLength));
Я пока до такого не дошел.
Двигаюсь со скоростью черепахи

2023-01-29 18:01 UTC, FenZlo commented on src/sort-method.js
> +    if (a.length < b.length) {
Попробую так сделать. 
Просто ещё не могу оперировать так красиво

2023-01-29 18:02 UTC, FenZlo commented on tests/map-method.js
> +    assert.strictEqual(mapMethod([2,3,4,5,6,7,8,9]), true);
Я эту тему тоже не прошел :D 
Но слышал, что это крутая штука

2023-01-29 18:03 UTC, FenZlo commented on tests/map-method.js
> +test('Concat with string', t => {
Пока сложнааа

2023-01-30 18:06 UTC, AtnesNess approved these changes

2023-01-30 18:06 UTC, AtnesNess commented on src/map-method.js
> +function makeRandomLetter(length) {
все еще создается такое впечатление :D

2023-01-30 18:06 UTC, AtnesNess commented on tests/map-method.js
> +    const resultArray = mapConcatRandomLetters(initialArray, 0);
кажется тут можно сравнить что массивы идентичны

2023-01-30 18:06 UTC, AtnesNess commented on tests/sort-method.js
> +    const initialArrayCopy = [...initialArray]; //Spred опператор прочитать отдельно. Тут мы копируем все значения из одного массива в другой
с кайфом

2023-02-01 08:24 UTC, vgneery approved these changes
исправь еще мелкие помарки и можно мержить, красава!

2023-02-01 08:24 UTC, vgneery commented on tests/filter-by-query.js
> +test('Filter by query', t => {
тут два теста с одинаковыми названиями, лучше конечно продумать более релевантные названия для каждого теста. Тест обычно звучит так: "Проверка такой-то функции в таких-то условиях"

2023-02-01 08:24 UTC, vgneery commented on tests/map-method.js
> +test('Check length each elements with default parametrs', t => {
```suggestion
test('Check length each elements with default parameters', t => {
```

2023-02-01 08:24 UTC, vgneery commented on tests/map-method.js
> +    }, new Error('Count can not be a negetive number'));
```suggestion
    }, new Error('Count parameter can not be a negative number'));
```

2023-02-04 09:26 UTC, merged