Домашнее задание на функцию-генератор псевдослучайных целочисленных последовательностей
FenZlo/Homework pull request #4
Opened 2023-02-04 19:00 UTC by FenZlo

2023-02-06 11:19 UTC, vgneery requested changes
Чуть подправить и будет воще кайфец!

2023-02-06 11:19 UTC, vgneery commented on src/number-generator.js
> +    if (typeof config === 'object' && config !== null && Object.keys(config).length === 3) {
тут хорошо сделано, но добавлю несколько полезных моментов:
- для более удобного чтения кода можно валидацию вынести наверх функции, а снизу оставить то, что ты хочешь вернуть. Закину снизу пример, сравни удобность чтения
- мы проверяем, что у нас в объекте обязательно должно быть 3 ключа, но в теории мы можем 3 любых ключа закинуть в функцию, а не те которые нам нужны + могут быть дефолтные настройки, например. Я бы тут оставил проверку на объект и null, убрал проверку на 3 ключа и добавил проверку на конкретные свойства, например.

```js
function generateNumberSequence(config) {
    if (typeof config !== 'object' || config === null) {
        throw new Error('Config param should be an object');
    }

    if (!config.count) {
        throw new Error('Config.count param should be defined');
    }

    const rangeMin = config.rangeMin || 0; // тут мы в переменную сетим либо поле из объекта, либо 0 если поля такого в объекте нет
    const rangeMax = config.rangeMax || 9;

    return () => {
        let result = [];
        for (i = 0; i < config.count; i++) {
            result.push(Math.floor(Math.random() * rangeMax) + rangeMin);
        }
        return result;
    };
}
```

2023-02-06 11:19 UTC, vgneery commented on tests/number-generator.js
> +    });
что-то форматирование кода поплыло немного

2023-02-06 11:19 UTC, vgneery commented on tests/number-generator.js
> +        assert.strictEqual(seq.length, 5);
тут я бы еще сравнил, что все элементы массива находятся в рамках чисел от 0 до 10

2023-02-09 02:19 UTC, AtnesNess commented on src/number-generator.js
> +if (typeof config !== 'object' || config === null) {
все тело функции надо бы отсупить, а то оч неудобно читать

2023-02-09 02:19 UTC, AtnesNess commented on tests/number-generator.js
> +test('Check generator of numbers from 0 to 10, the number of numbers is 5', t => {
лучше сказать `the amount of items`

2023-02-09 02:19 UTC, AtnesNess commented on tests/number-generator.js
> +        seq;
кажись лишнее

2023-02-09 02:19 UTC, AtnesNess commented on tests/number-generator.js
> +        count: 5,
на тесты с рандомом лучше делать выборку на 10000+ элементов, чтобы наверняка

2023-02-09 19:50 UTC, AtnesNess commented on src/number-generator.js
> +    return () => {
тут ты тоже создал функцию, поэтому надо все тело отступить

2023-02-09 19:50 UTC, AtnesNess commented on src/number-generator.js
> +    };
здесь ревьюер путается почему две фигурные скобки идут друг за другом с одним и тем же отступом. Только потом понимая что там была еще одна функция

2023-02-09 19:50 UTC, AtnesNess commented on tests/number-generator.js
> +    });
кажется эта скобочка должны быть в самом начале строки

2023-02-09 19:50 UTC, AtnesNess commented on tests/number-generator.js
> +    });
отступы поехали

2023-02-09 19:50 UTC, AtnesNess commented on tests/number-generator.js
> +        assert.strictEqual(seq.length, 5);
тут я вообще запутался. Зачем доп отступ для assert и почему закрывающаяся скобка стоит с отступом?

для меня это автоматом читается как  
```
    const seq3 = numberGenerator2(() => {
        assert.strictEqual(seq3.length, 3);
    });
```

пока я не посмотрю внимательнее

2023-02-12 12:49 UTC, FenZlo commented on src/number-generator.js
> +if (typeof config !== 'object' || config === null) {
Теперь у меня Линтер и у меня есть щит от shit

2023-02-12 12:49 UTC, vgneery approved these changes

2023-02-12 12:49 UTC, merged